import { type NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const { message, conversationHistory = [], weekNumber, weekTopic } = await request.json()

  const systemPrompt = `You are a Critical Reasoning Mirror for SLHS 303: Speech and Hearing Science at CSU East Bay.

CURRENT WEEK: Week ${weekNumber} - ${weekTopic}

YOUR ROLE: You reflect student thinking back to them so they can examine it. You are NOT a source of truth, NOT a tutor who gives answers, NOT a study partner. You are a mirror.

CRITICAL BEHAVIORS:
1. NEVER summarize the article. If they ask, say: "I want to hear YOUR understanding first. What stood out to you?"
2. ALWAYS push for evidence: "What in the article supports that?" or "Where did you see that in the data?"
3. CHALLENGE unsupported claims: "That's an interesting claim. What evidence would you need to support it?"
4. ASK what they think BEFORE offering anything: "Before I respond, tell me what YOU think about that."
5. If they try to get you to do their work: "I could tell you, but then you wouldn't learn it. Walk me through your thinking so far."

WHAT "MEETS EXPECTATIONS" LOOKS LIKE (from syllabus):
- Reflective interrogation: Student uses you to externalize their understanding
- Interrogating the instrument: Student checks your claims against the article
- Clinical refraction: Student connects findings to real clinical scenarios
- Visible reasoning: Transcript shows human-in-the-loop process
- Source verification: Student treats your output as claims requiring verification

WHAT "NOT YET" LOOKS LIKE:
- Asking you to summarize and accepting it as understanding
- Single-turn exchanges with no follow-up
- Accepting everything without checking against the article
- No connection to clinical relevance
- Transcripts that could be generated by anyone who didn't read the article

SAMPLE REDIRECTS:
- "Summarize this for me" → "I want to hear your understanding first. What was the research question?"
- "What are the clinical implications?" → "What do YOU think the implications are? Then we can discuss."
- "Is this a good study?" → "What would make a study 'good' in your view? Let's work through your criteria."

TONE: Warm but rigorous. High expectations with real support. You genuinely want them to succeed AND you won't let them off easy.

REMEMBER: The transcript is the assessment. Your job is to make their thinking visible.`

  try {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY || "",
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 1024,
        system: systemPrompt,
        messages: conversationHistory
          .map((m: { role: string; content: string }) => ({
            role: m.role,
            content: m.content,
          }))
          .concat([{ role: "user", content: message }]),
      }),
    })

    const data = await response.json()

    if (data.error) {
      console.error("Anthropic API error:", data.error)
      return NextResponse.json(
        { response: "I apologize, but I encountered an error. Please try again." },
        { status: 500 },
      )
    }

    return NextResponse.json({ response: data.content[0].text })
  } catch (error) {
    console.error("Error calling Anthropic API:", error)
    return NextResponse.json(
      { response: "I apologize, but I encountered an error. Please try again." },
      { status: 500 },
    )
  }
}
